# Generated by Django 5.0.3 on 2024-03-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=15)),
                ('autor', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=15)),
            ],
        ),
    ]
