# Generated by Django 5.0.3 on 2024-03-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0002_autor_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='pais',
        ),
    ]
