# Generated by Django 5.0.3 on 2024-03-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0003_remove_autor_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tarifa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
