# Generated by Django 5.0.3 on 2024-03-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0004_empleado_edad_empleado_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='cantidad_libros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
