# Generated by Django 5.0.3 on 2024-03-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0005_autor_cantidad_libros_autor_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='ventas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
